version: '2' 


services:
  express: 
    build: Express-server 
    ports:
      - "3000:3000"
    depends_on:
      - stagedbone
      
  stagedbone: 
    image: mongo 
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  