apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stage-db-pvc
  namespace: stage-app-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi





      


 

 
  
