apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stage-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  
