apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stage-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi





      
 # kubectl get pod -n kube-system -o wide | grep api1
 # journalctl -u kubelet -f 

 

 
  
