apiVersion: v1
kind: Service
metadata:
  labels:
    name: stagedb
  name: stagedb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31516
  selector:
    app: stagedb