apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-db-dep
  namespace: stage-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stage-db-dep
  template:
    metadata:
      labels:
        component: stage-db-dep
  spec: 
     volumes:
        - name: stage-db-claim
          persistentVolumeClaim:
            claimName: stage-db-pvc
     containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017 
          volumeMounts:
          - name: stage-db-claim
            mountPath: /data/db       
            
            
---


apiVersion: v1
kind: Service
metadata:
  name: stage-db-svc
  namespace: stage-app-prod
spec:
  type: ClusterIP
  selector:
    component: stage-db-dep
  ports:
    - port: 27017
      targetPort: 27017           