apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stage-app # name of object created by the config file  
spec: # specify the caractirstique of the deployment
  replicas: 2 # number of pod gonna make using the tamplate 
  selector: # use selector to related with service yaml
    matchLabels:
      app: stage-app # the Id to connect with service yaml could be anything like company : djezzy
  template: # pod Tamlate definition 
    metadata:
      labels: # the Id to connect with service yaml could be anything like company : djezzy 
        app: stage-app
    spec:
      containers: # all information about the container
      - name: stage-app # name of the container should be (stagedb in mongodb deployment file same as code source)
        image: djezzy-api3:5000/stageapp:v1.5  # based image container could be from docekr hub or local image mongoku 
        imagePullPolicy: IfNotPresent # image download from docker hub 
        ports: # all information about the ports
        - containerPort: 3000 # container port in (case expose in Dockerfile)
          name: stage-app-port # 




# to apply the config file  : kubectl apply -f stage-deployment.yaml
# to remove an object u must use : kubectl delete -f 'config file'
# to update an object  u must delete deployment and created agin soulution 1
# build image with tag and refer to it  ( docker build -t stageapp:v1.3)
# docker run -d --name mongoku -p 3100:3100 huggingface/mongoku
# update image with the following cammand :{kubectl set image deployment/stage-deployment stage-app=djezzy-api3:5000/stageapp:v2 }
# docker tag efefb83b7882 djezzy-api3:5000/stageapp:v1.5
#docker push djezzy-api3:5000/stageapp:v1.5


